### ISSUE TITLE
Support for Owncloud 9

### ISSUE THREAD

**Issue by bjoernv** [leizh/owncloud-files_clipboard#11]
The app files_clipboard does not seem to be compatible with Owncloud 9 (tested with 9.0.0). At first min-version and max-version is missing in files_clipboard/appinfo/info.xml. So Owncloud 9 accepts the apps with the hint "This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later."

The Copy and Cut links work without an error message. But Paste hangs until the browser gets a timeout. In data/owncloud.log I see this message after executing Paste:

{"reqId":"MhHa3GKtRUBpNp++htzz","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined method OC_L10N::get() at \/srv\/www\/htdocs\/owncloud\/apps\/files_clipboard\/ajax\/clipboard.php#43","level":3,"time":"2016-03-13T18:59:02+00:00"}

Some notes about the environment:
- Apache 2.4.18
- PHP 5.6.18
- openSUSE Tumbleweed
- Owncloud 9.0.0 from Distribution: ce:9.0 / openSUSE_Leap_42.1
- installation directory: /srv/www/htdocs/owncloud
- owncloud is upgraded from 8.1 over 8.2 to 9.0

**Comment by bjoernv** [comment]
The fix for "Call to undefined method OC_L10N::get()" is easy. Just delete the line

$l = OC_L10N::get('files_clipboard');

$l is already defined correctly at the beginning of the PHP file

$l = \OC::$server->getL10N('files_clipboard');

See attached patch.
[oc_app-files_clipboard-incorrect_l10n_call.patch.txt](https://github.com/leizh/owncloud-files_clipboard/files/171241/oc_app-files_clipboard-incorrect_l10n_call.patch.txt)

**Comment by compuguy** [comment]
@bjoernv have you attempted to sent the repo owner a pull request by chance?

**Comment by bjoernv** [comment]
No, only a patch. Should I sent a pull request?

**Comment by leizh** [comment]
I have merged your patch in 0.5.0 alongside an API change which should correct the problems on the external storages. Can you give it a try ?

**Comment by bjoernv** [comment]
@leizh I tested some basic use-cases (copy-paste and cut-paste files and directories) between multiple directories. This works.

**Comment by leizh** [comment]
Thanks. I close this issue.
