### ISSUE TITLE
Support for Nextcloud 11

### ISSUE THREAD

**Issue by zerojay** [leizh/owncloud-files_clipboard#13]
Files_clipboard cannot be installed on Nextcloud 11 as the following is shown:

Files_clipboard 0.5.0:
This app has no minimum Nextcloud version assigned. This will cause an error in the future.
This app cannot be installed because the following dependencies are not fulfilled:
Server version 10 or lower is required.

**Comment by leizh** [comment]
The application is now available at https://apps.nextcloud.com/apps/files_clipboard .
