### ISSUE TITLE
Owncloud 10 Integrity Check Error

### ISSUE THREAD

**Issue by dlandon** [leizh/owncloud-files_clipboard#16]
There is an integrity check error showing because of the signature file being invalid.
- files_clipboard
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Would appreciate you fixing this.

**Comment by leizh** [comment]
This app is now on the [marketplace](https://marketplace.owncloud.com/apps/files_clipboard), you can install it to resolve this.
