### ISSUE TITLE
can not be activated + won't show in available apps

### ISSUE THREAD

**Issue by nextgen-networks** [leizh/owncloud-files_clipboard#19]
Hi developer(s),

this cool extension can be installed by direct copy to apps but sadly not activated on nextcloud 12.02.
![2017-08-21 files_clipboard app activation status](https://user-images.githubusercontent.com/21206978/29510572-8d34429e-865c-11e7-839c-85d2383f44e0.jpg)

next (less important) issue (whis ;-))
is it possible to let the app install direct via available app within nextcloud?

Thanks for your hard work!

Greetings from Hamburg/Germany

Ralf

**Comment by e-alfred** [comment]
I have the same problem that this app shows up on https://apps.nextcloud.com but not in the integrated Nextcloud app store on the instance itself. This prevents installation directly from within the web interface of Nextcloud.

My system:

Nextcloud 12.0.2
Ubuntu 16.04 with Apache 2.4 and PHP 7.0

**Comment by JimmyKater** [comment]
@nextgen-networks 

> this cool extension can be installed by direct copy to apps but sadly not activated on nextcloud 12.02.

i just did it... and i even could activate it.
did you take care about the ownership of the new files? maybe a chown is gonna fix it?

**Comment by leizh** [comment]
The app do not show on my nextcloud instance neither. I do not know why. I have tried to change the category to 'files' (0.6.3), unsuccessfully.

**Comment by JSoko** [comment]
Also the update doesn't work automatic. You have to copy it manualy to the apps-folder...

**Comment by nextgen-networks** [comment]
OK found the reason (not really an error) for the activation problem:
Original value in info.xml: `<php min-version="5.4" max-version="7.0" />`

Because i'm using PHP 7.1 this wont work for me (Remembrance of myself: check those basic things first ;-) )

Simple solution is canging the value in info.xml to: `<php min-version="5.4" max-version="7.1" />`

**Comment by e-alfred** [comment]
@leizh Maybe filing an issue in the Appstore repository could resolve the issue?

https://github.com/nextcloud/appstore/issues

**Comment by JimmyKater** [comment]
> Simple solution is changing the value in info.xml to: <php min-version="5.4" max-version="7.1" />
apparently this fixes the issue and thus it should be closed.

@jsoko and @e-alfred's note about app not showing up in appstore and thus no-autoupdate are valid but don't rellay belong to original thread...

**Comment by nextgen-networks** [comment]
@JimmyKater 
i think this can be closed if the corresponding change has been accepted and committed to repo
if done the developer or i will close this issue :-)

The title of this issue also contains an request for the app store visibility therefore i think it's part of the original thread. Maybe it's an good idea to open an new feature-request ticket once the main reason I've opened this issue has been fixed/committed.

**Comment by JimmyKater** [comment]
> The title of this issue also contains an request for the app store visibility.

you're right... sorry. i missed that.

**Comment by leizh** [comment]
The store app visibility problem should be fixed (0.6.4).

**Comment by JSoko** [comment]
@leizh
Yes...
...Update from 0.6.3 was shown and the update was made automaticily.

Thank You!

**Comment by JimmyKater** [comment]
@leizh 
good work! even update from 0.6.2 was shown and could made from NC-instance via apps.
