### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dasaweb** [leizh/owncloud-files_clipboard#21]
Hi, 

if I try to install the app using my Nextcloud app store I get this error:

> Client error response [url] https://dev.lez.name/files_clipboard.tar.gz [status code] 404 [reason phrase] Not Found

The same error appears if I try to download the app on the project page: https://apps.nextcloud.com/apps/files_clipboard/releases?platform=12

Thank you for your help!
Daniel

**Comment by marfal** [comment]
Same here. Please fix the link to the installer. Thank you.

**Comment by dasaweb** [comment]
It seems to be fixed. Better fixing the issue without saying a word than vice versa ;-)
