### ISSUE TITLE
Error during copy of multiple shared files gives access to all files of that user

### ISSUE THREAD

**Issue by ondrulus** [leizh/owncloud-files_clipboard#23]
Hi,
on Nextcloud 12.0.0 with Files clipboard  0.6.4 happened this:
-Another user shared 2 files with me (files located in root of another users directory and gave me full access rights).
-I ticked those two files in web browser and than clicked copy. I switched to my other directory and clicked paste.
-Instead coping those two files, two directories were created. Names of the directories were same as names of the files (actual names were: "bit locker key.pdf" and "name.key")
-Clicking on any of those directories shows 4 new folders: cache, files_versions, files_trashbin, files (so same structure as nextcloud saves files in users directories)
- opening files folder for example gives access to ALL files and folders of the user that shared just two files with me (his other files were not shared with anyone)
- I can open his files, download his files, create new files. On the other hand deleting always fails, and try to modify file makes a new modified copy in same directory instead of just modifying it.
- Also deleting those 2 wrongfully created directories fails (web gives fail error, desktop client shows error upon sync)

This issue seems very critical to me.

**Comment by leizh** [comment]
I have released the new branch 0.7 (on github only) which should resolve this problem. Can you test it before it goes public ? I have not managed to reproduce your problem.

**Comment by ondrulus** [comment]
Hi, just did tried to do the exactly same thing with your new 0.7 
version (nextcloud-files_clipboard-0.7.0.tar.gz) and this time 
everything was in order. No bug or error.
But since this happed on my production environment I have it now on 
Nextcloud 12.0.4. versus 12.0.0 when I initially reported the bug. And I 
no longer have older backup with 12.0.0.
But I guess that does not matter.

BTW: I really appreciate your work on this project.



Dne 13.1.2018 21:27, leizh napsal:
