### ISSUE TITLE
dutch translation

### ISSUE THREAD

**Issue by casperrutten** [leizh/owncloud-files_clipboard#24]
[dutch translation.zip](https://github.com/leizh/owncloud-files_clipboard/files/1326701/dutch.translation.zip)

**Comment by leizh** [comment]
Can you provide the .po file for the futur contributions ?

**Comment by leizh** [comment]
Merged in f6d89fc9ffd3e391548f34eb9c9b12d070bec4c7.

**Comment by casperrutten** [comment]
yes, I can. I like your app very much

**Comment by casperrutten** [comment]
[clipboard_dutch_translation.zip](https://github.com/leizh/owncloud-files_clipboard/files/1624520/clipboard_dutch_translation.zip)
In the german .po file is a source text in the french language, should be english.
Kind regards

**Comment by leizh** [comment]
Thanks. I have fixed the .po files.
