### ISSUE TITLE
Add PHP 7.1 compatibility

### ISSUE THREAD

**Issue by GTT8** [leizh/owncloud-files_clipboard#27]
# Error:
This app cannot be installed because the following dependencies are not fulfilled:
- PHP with a version lower than 7.0 is required.

**Comment by dlandon** [comment]
I'm trying to update to php 7.1.  Can this dependency be error be fixed?

This app cannot be installed because the following dependencies are not fulfilled:

PHP with a version lower than 7.0 is required.

**Comment by leizh** [comment]
Fixed by d4c2b2e126d937c363a703d20bcd425ac1967fd3 .
