### ISSUE TITLE
Cut does not respect Read Only Share

### ISSUE THREAD

**Issue by soloam** [leizh/owncloud-files_clipboard#29]
Hello, I noticed if I share a folder as read only, I'm able to cut a file inside the share with read only, and then paste it (move it) to outside the share, deleting the file/folder on the share. I think that the cut and paste functionality should respect the read only share.

Thank you

**Comment by soloam** [comment]
Is this really a bug or any miss configuration on my side?

**Comment by qm2k** [comment]
Same problem here. Clearly a serious problem.

**Comment by MercuryOZ** [comment]
>  I noticed if I share a folder as read only, I'm able to cut a file inside the share with read only, and then paste it (move it) to outside the share, deleting the file/folder on the share. I think that the cut and paste functionality should respect the read only share.

Hi. I just caught the same BUG. Can you please fix it? It's a serious one.
Thank you

**Comment by soloam** [comment]
I disabled the plugin because of this... To dangerous to leave active.

**Comment by leizh** [comment]
I'm working on a new branch which uses the webdav API for copies and moves. This will prevent this kind of problem. I hope to release it this week in beta.

**Comment by leizh** [comment]
I have released the new branch 0.7 (on github only) which should resolve this problem. Can some people test it before it goes public ?

**Comment by soloam** [comment]
How can I merge this into my server? I normally update from the web interface. 

Thank You

**Comment by leizh** [comment]
The release is now public. You can download it from the marketplace.

**Comment by qm2k** [comment]
Updated from marketplace, seem to work fine here.
