### ISSUE TITLE
No cut on level one of external storage

### ISSUE THREAD

**Issue by loeffelpan** [leizh/owncloud-files_clipboard#30]
I'm very happy with files_clipboard.
But there is no "cut"-option on all directories and files in "external storage"-folders.
Subdirectories and files in subdirectories offer that option.
Every other file outside of "external storage"-folders offers that option too.

**Comment by kuimovvg** [comment]
Confirm, i have the same problem in GoogleDrive external storage

**Comment by loeffelpan** [comment]
Seems to have something to do with the permissions.
While trying to find a wordaround for me i noticed, that mounting the parent folder on my harddrive doesn't solve this issue.
But my apache-user doesn't have permissions there. So, it's not the first level of external storage, but the first level with writing permissions with no cut option.

**Comment by leizh** [comment]
This is normaly fixed with e676e61b95abdd0fdce53f8bada334f6ac8416e3. I should release a new public version next week.
