### ISSUE TITLE
support nc 13

### ISSUE THREAD

**Issue by JimmyKater** [leizh/owncloud-files_clipboard#32]
my can-i-update-app tells me that files_clipboard (v 0.6.5) isn't nc 13 ready, yet. 

true?

**Comment by violoncelloch** [comment]
probably a change of the `max-version` in `info.xml` would be sufficient...?

**Comment by e-alfred** [comment]
This app won't be needed anymore on NC 13 because the features are implemented into the core now:

https://github.com/nextcloud/server/issues/3206
https://github.com/nextcloud/server/pull/6014
https://github.com/nextcloud/server/pull/6273

**Comment by violoncelloch** [comment]
Ahh, thanks!

**Comment by JimmyKater** [comment]
@e-alfred 
i hoped so as well and then i checked jasonbaytons demo-instance if nc 13 (beta 2)... and no. it's not really featured... well... in parts it IS featured but the app contains of more possibilities on how to treat files

**Comment by JimmyKater** [comment]
hey. they have worked on the features of nc13, indeed. except for "cut" it's all featured. so i'm gonna close this issue.

**Comment by e-alfred** [comment]
@JimmyKater Well, "move" should be a replacement for "cut" I was told.

**Comment by JimmyKater** [comment]
@e-alfred *hehehe*
backset-driver that i am: to be really precise "move" includes "cut", of course. 
but "cut" gets it into buffer and you can access it from there. not sure about "move".
anyways... it's solved in a acceptable way :o)
