### ISSUE TITLE
Compatibility with Nextcloud 13

### ISSUE THREAD

**Issue by GLLM** [leizh/owncloud-files_clipboard#34]
As of now, the application is not considered compatibel with Nextcloud 13,, could  you please update it if it is ?
Thanks

**Comment by JSoko** [comment]
From NC 13 on, the features are implemented into the core:

nextcloud/server#3206
nextcloud/server#6014
nextcloud/server#6273
https://github.com/leizh/owncloud-files_clipboard/issues/32

**Comment by leizh** [comment]
Indeed, I do not intend to maintain this app on Nextcloud 13.
